export const fruitColors = {
  apple: "#F5F5DC",
  avocado: "#B5CC99",
  banana: "#FFF2CC",
  cucumber: "#CDEAC0",
  dragonfruit: "#FFB6C1",
  durian: "#FFFACD",
  grape: "#D1C4E9",
  guava: "#CBDDA9",
  kiwi: "#E2F0D9",
  lemon: "#FFFFE0",
  lychee: "#FFC1A1",
  mango: "#FFE0B2",
  orange: "#FFDAB9",
  papaya: "#FFEBCC",
  pear: "#E9F3D4",
  pineapple: "#FAF0D7",
  pomegranate: "#F9C2C2",
  strawberry: "#FFC0CB",
  tomato: "#FF9988",
  watermelon: "#FFCCCB",
};
